version: '3.8'
services:
    postgres:
    image: postgres
    environment:
        POSTGRES_DB: "yg"
        POSTGRES_USER: "admin"
        POSTGRES_PASSWORD: "admin"
    volumes:
        - ./init-sql:/docker-entrypoint-initdb.d
    ports:
        - "5432:5432"
    colonel:
        build:
            context: ./
        restart: always
        ports:
            - "8888:8080"
        networks:
            - rabbit
networks:
    rabbit:
        name: common
        # external: true
